imports:
  - path: "bucket-template.jinja"

resources:
  - name: "jenkins-backend"
    type: "bucket-template.jinja"
    properties:
      bucket_name: "jenkins-backend"
      region: "us-central1"
      storage_class: "STANDARD"